<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LLLGMOJ" failures="1" tests="4" name="RetryMulitple" time="0.083" errors="0" timestamp="27 Sep 2022 04:01:03 GMT">
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test1" time="0.014">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test1" time="0.003">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test1" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at runTimeRetryfailedTc.Test001.Test1(Test001.java:13)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test2" time="0.001"/>
</testsuite> <!-- RetryMulitple -->
